blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://ielts-stud.ai/en/support
    about: Things don't work as intended
  - name: Bug
    url: https://ielts-stud.ai/vi/support
    about: IELTS STUDY AI Bug
